baseURL = "https://stalwart-paletas-2c0a7e.netlify.app/"
title = "KKM Autoshop"
author = "EV Advisory"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['services']

  googleFonts = true

  [params.logo]
    main = "img/logo/kkm_logo_rsz2.svg"
    alt = "KKM Autoshop Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-2"

  [params.site]
    name = "KKM Autoshop"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "KKM Auto Shop, A family business automotive mechanic in the GTA"
    meta_og_title = "KKM Auto"
    meta_og_type = "website"
    meta_og_url = "https://kkmautoshop.com"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Mechanic and auto services family business within the GTA"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@kkm.autoshop"
    meta_twitter_creator = "@kkm.autoshop"

[menu]

  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='fa-solid fa-car-side text-2x1'></i>"
      weight = 2
  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='fa-solid fa-car-side text-2x1'></i>"
      weight = 3
